/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmitRouteImport } from './routes/admit'
import { Route as Ass001RouteImport } from './routes/ass001'
import { Route as AssaysRouteImport } from './routes/assays'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HmeRouteImport } from './routes/hme'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LogRouteImport } from './routes/log'
import { Route as NullifierRouteImport } from './routes/nullifier'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TrainRouteImport } from './routes/train'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmitRoute = AdmitRouteImport.update({
  id: '/admit',
  path: '/admit',
  getParentRoute: () => rootRouteImport,
} as any)
const Ass001Route = Ass001RouteImport.update({
  id: '/ass001',
  path: '/ass001',
  getParentRoute: () => rootRouteImport,
} as any)
const AssaysRoute = AssaysRouteImport.update({
  id: '/assays',
  path: '/assays',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HmeRoute = HmeRouteImport.update({
  id: '/hme',
  path: '/hme',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const NullifierRoute = NullifierRouteImport.update({
  id: '/nullifier',
  path: '/nullifier',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admit': typeof AdmitRoute
  '/ass001': typeof Ass001Route
  '/assays': typeof AssaysRoute
  '/bench': typeof BenchRoute
  '/claims': typeof ClaimsRoute
  '/graph': typeof GraphRoute
  '/hme': typeof HmeRoute
  '/ledger': typeof LedgerRoute
  '/log': typeof LogRoute
  '/nullifier': typeof NullifierRoute
  '/safety': typeof SafetyRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admit': typeof AdmitRoute
  '/ass001': typeof Ass001Route
  '/assays': typeof AssaysRoute
  '/bench': typeof BenchRoute
  '/claims': typeof ClaimsRoute
  '/graph': typeof GraphRoute
  '/hme': typeof HmeRoute
  '/ledger': typeof LedgerRoute
  '/log': typeof LogRoute
  '/nullifier': typeof NullifierRoute
  '/safety': typeof SafetyRoute
  '/train': typeof TrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admit': typeof AdmitRoute
  '/ass001': typeof Ass001Route
  '/assays': typeof AssaysRoute
  '/bench': typeof BenchRoute
  '/claims': typeof ClaimsRoute
  '/graph': typeof GraphRoute
  '/hme': typeof HmeRoute
  '/ledger': typeof LedgerRoute
  '/log': typeof LogRoute
  '/nullifier': typeof NullifierRoute
  '/safety': typeof SafetyRoute
  '/train': typeof TrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admit'
    | '/ass001'
    | '/assays'
    | '/bench'
    | '/claims'
    | '/graph'
    | '/hme'
    | '/ledger'
    | '/log'
    | '/nullifier'
    | '/safety'
    | '/train'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admit'
    | '/ass001'
    | '/assays'
    | '/bench'
    | '/claims'
    | '/graph'
    | '/hme'
    | '/ledger'
    | '/log'
    | '/nullifier'
    | '/safety'
    | '/train'
  id:
    | '__root__'
    | '/'
    | '/admit'
    | '/ass001'
    | '/assays'
    | '/bench'
    | '/claims'
    | '/graph'
    | '/hme'
    | '/ledger'
    | '/log'
    | '/nullifier'
    | '/safety'
    | '/train'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmitRoute: typeof AdmitRoute
  Ass001Route: typeof Ass001Route
  AssaysRoute: typeof AssaysRoute
  BenchRoute: typeof BenchRoute
  ClaimsRoute: typeof ClaimsRoute
  GraphRoute: typeof GraphRoute
  HmeRoute: typeof HmeRoute
  LedgerRoute: typeof LedgerRoute
  LogRoute: typeof LogRoute
  NullifierRoute: typeof NullifierRoute
  SafetyRoute: typeof SafetyRoute
  TrainRoute: typeof TrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admit': {
      id: '/admit'
      path: '/admit'
      fullPath: '/admit'
      preLoaderRoute: typeof AdmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ass001': {
      id: '/ass001'
      path: '/ass001'
      fullPath: '/ass001'
      preLoaderRoute: typeof Ass001RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assays': {
      id: '/assays'
      path: '/assays'
      fullPath: '/assays'
      preLoaderRoute: typeof AssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hme': {
      id: '/hme'
      path: '/hme'
      fullPath: '/hme'
      preLoaderRoute: typeof HmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nullifier': {
      id: '/nullifier'
      path: '/nullifier'
      fullPath: '/nullifier'
      preLoaderRoute: typeof NullifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmitRoute: AdmitRoute,
  Ass001Route: Ass001Route,
  AssaysRoute: AssaysRoute,
  BenchRoute: BenchRoute,
  ClaimsRoute: ClaimsRoute,
  GraphRoute: GraphRoute,
  HmeRoute: HmeRoute,
  LedgerRoute: LedgerRoute,
  LogRoute: LogRoute,
  NullifierRoute: NullifierRoute,
  SafetyRoute: SafetyRoute,
  TrainRoute: TrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
