# Compiled lexical program from CODEBASE_TOME boxed rules.
# Frequency-ranked semantic invariants only. Not the 5207 latex repeats.

PERMIT  UNKNOWN         RESOLVE
FORBID  UNKNOWN         CONSEQUENCE
FORBID  UNKNOWN         EXECUTE
FORBID  UNASSESSED      CONSEQUENCE
FORBID  UNASSESSED      EXECUTE
FORBID  ARCHIVE         EXECUTE     unless CURRENT_GRANT
FORBID  REJECTED        UNASSESSED

NIMPL   BLOCKED_BRANCH  BLOCKED_TREE
NIMPL   EMPTY_PENDING   RELEVANT_NEW
NIMPL   PI_W_EQ_R       W_EQ_INV_PI
NIMPL   DELTA_AUDIT     DELTA_CONTROL
NIMPL   DELTA_RENDER    DELTA_CONTROL
NIMPL   DELTA_EXPORT    DELTA_CONTROL

REQUIRE CURRENT_SURFACE LAWFUL_SUCCESSOR
REQUIRE MEASURE         UNCERTAINTY     # don't encode what you can measure

NIMPL   SPACED_LAYOUT    SOURCE_UNEDITED
FORBID  MUSCLE_WORK      FLOW           unless OPEN_RAMP

SEARCH  WIDE
CONSEQUENCE TIGHT
